//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd", IsNullable = false)]
public partial class ModifyMeterProgramIndiaAMI
{
    
    private string endpointModelField;
    
    private string meterFirmwareVersionField;
    
    private string moduleFirmwareVersionField;
    
    private string programNameField;
    
    
    private string programDescriptionField;
    
    private int programCRCField;
    
    private RequiredMeterOperation[] meterOperationField;
    
    /// <remarks/>
    public string EndpointModel {
        get {
            return this.endpointModelField;
        }
        set {
            this.endpointModelField = value;
        }
    }
    
    /// <remarks/>
    public string MeterFirmwareVersion {
        get {
            return this.meterFirmwareVersionField;
        }
        set {
            this.meterFirmwareVersionField = value;
        }
    }
    
    /// <remarks/>
    public string ModuleFirmwareVersion {
        get {
            return this.moduleFirmwareVersionField;
        }
        set {
            this.moduleFirmwareVersionField = value;
        }
    }
    
    /// <remarks/>
    public string ProgramName {
        get {
            return this.programNameField;
        }
        set {
            this.programNameField = value;
        }
    }
    
    
    /// <remarks/>
    public string ProgramDescription {
        get {
            return this.programDescriptionField;
        }
        set {
            this.programDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public int ProgramCRC {
        get {
            return this.programCRCField;
        }
        set {
            this.programCRCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MeterOperation")]
    public RequiredMeterOperation[] MeterOperation {
        get {
            return this.meterOperationField;
        }
        set {
            this.meterOperationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd", IsNullable = false)]
public enum ProgramName {

    /// <remarks>
    /// Meter Configuration Category A includes the configurations which require CC to InitPoll the configurations
    /// </remarks>
    MeterConfigurationCategoryA,

    /// <remarks>
    /// Meter Configuration Category B includes the configurations which DOESN'T require CC to InitPoll the configurations
    /// </remarks>
    MeterConfigurationCategoryB,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd", IsNullable = false)]
public enum ConfigType
{

    /// <remarks/>
    DemandIP,

    /// <remarks/>
    SurveyIP,
    /// <remarks/>
    BillingDateTime,
    /// <remarks/>
    OverVoltage,
    /// <remarks/>
    LowVoltage,
    /// <remarks/>
    OverLoad,
    /// <remarks/>
    VeryLowPF,
    /// <remarks/>
    MissingPotential,
    /// <remarks/>
    NeutralDisturbance,
    /// <remarks/>
    MagneticInfluence,
    /// <remarks/>
    CurrentReversal,
    /// <remarks/>
    CurrentImbalance,
    /// <remarks/>
    OverCurrent,
    /// <remarks/>
    CTOpen,
    /// <remarks/>
    CTShort,
    /// <remarks/>
    VoltageUnb,
    /// <remarks/>
    PowerOnOff,
    /// <remarks/>
    FutureDayProfile,
    /// <remarks/>
    WeekProfile,
    /// <remarks/>
    SeasonProfile,
    /// <remarks/>
    FutureActivationDate,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Hunt.EPIC.Utilities/1.0/ModifyMeterProgramIndiaAMI.xsd", IsNullable = false)]
public partial class RequiredMeterOperation {

    private string configTypeField;
   
    
    private string configDescriptionField;
    
    private byte[] binaryDataField;
    
    /// <remarks/>
    public string ConfigType
    {
        get {
            return this.configTypeField;
        }
        set {
            this.configTypeField = value;
        }
    }
   
    
    /// <remarks/>
    public string ConfigDescription {
        get {
            return this.configDescriptionField;
        }
        set {
            this.configDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] BinaryData {
        get {
            return this.binaryDataField;
        }
        set {
            this.binaryDataField = value;
        }
    }
}
