//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8762
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://iec.ch/TC57/2011/schema/message", IsNullable=false)]
public partial class RequestMessage {
    
    private RequestMessageHeader headerField;
    
    private RequestMessagePayload payloadField;
    
    /// <remarks/>
    public RequestMessageHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public RequestMessagePayload Payload {
        get {
            return this.payloadField;
        }
        set {
            this.payloadField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class RequestMessageHeader {
    
    private string verbField;
    
    private string nounField;
    
    private decimal revisionField;
    
    private System.DateTime timestampField;
    
    private string sourceField;
    
    private string messageIDField;
    
    private string correlationIDField;
    
    /// <remarks/>
    public string Verb {
        get {
            return this.verbField;
        }
        set {
            this.verbField = value;
        }
    }
    
    /// <remarks/>
    public string Noun {
        get {
            return this.nounField;
        }
        set {
            this.nounField = value;
        }
    }
    
    /// <remarks/>
    public decimal Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime Timestamp {
        get {
            return this.timestampField;
        }
        set {
            this.timestampField = value;
        }
    }
    
    /// <remarks/>
    public string Source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    public string MessageID {
        get {
            return this.messageIDField;
        }
        set {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    public string CorrelationID {
        get {
            return this.correlationIDField;
        }
        set {
            this.correlationIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/schema/message")]
public partial class RequestMessagePayload {
    
    private GetEndDeviceSecurityConfig getEndDeviceSecurityConfigField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
    public GetEndDeviceSecurityConfig GetEndDeviceSecurityConfig {
        get {
            return this.getEndDeviceSecurityConfigField;
        }
        set {
            this.getEndDeviceSecurityConfigField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#", IsNullable=false)]
public partial class GetEndDeviceSecurityConfig {
    
    private GetEndDeviceSecurityConfigEndDeviceSecurity endDeviceSecurityField;
    
    /// <remarks/>
    public GetEndDeviceSecurityConfigEndDeviceSecurity EndDeviceSecurity {
        get {
            return this.endDeviceSecurityField;
        }
        set {
            this.endDeviceSecurityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
public partial class GetEndDeviceSecurityConfigEndDeviceSecurity {
    
    private GetEndDeviceSecurityConfigEndDeviceSecurityNames[] namesField;
    
    private GetEndDeviceSecurityConfigEndDeviceSecurityKeyEncryptionKey keyEncryptionKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Names")]
    public GetEndDeviceSecurityConfigEndDeviceSecurityNames[] Names {
        get {
            return this.namesField;
        }
        set {
            this.namesField = value;
        }
    }
    
    /// <remarks/>
    public GetEndDeviceSecurityConfigEndDeviceSecurityKeyEncryptionKey KeyEncryptionKey {
        get {
            return this.keyEncryptionKeyField;
        }
        set {
            this.keyEncryptionKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
public partial class GetEndDeviceSecurityConfigEndDeviceSecurityNames {
    
    private string nameField;
    
    private GetEndDeviceSecurityConfigEndDeviceSecurityNamesNameType nameTypeField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public GetEndDeviceSecurityConfigEndDeviceSecurityNamesNameType NameType {
        get {
            return this.nameTypeField;
        }
        set {
            this.nameTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
public partial class GetEndDeviceSecurityConfigEndDeviceSecurityNamesNameType {
    
    private string descriptionField;
    
    private string nameField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://iec.ch/TC57/2011/GetEndDeviceSecurityConfig#")]
public partial class GetEndDeviceSecurityConfigEndDeviceSecurityKeyEncryptionKey {
    
    private byte[] modulusField;
    
    private byte[] exponentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] modulus {
        get {
            return this.modulusField;
        }
        set {
            this.modulusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
}
