//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class SystemSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SystemSettings defaultInstance = ((SystemSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SystemSettings())));
        
        public static SystemSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS15959Part1Amd5RTCFormat {
            get {
                return ((bool)(this["IS15959Part1Amd5RTCFormat"]));
            }
            set {
                this["IS15959Part1Amd5RTCFormat"] = value;
            }
        }
    }
}
