//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CabconPMP.Images {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class DefaultSettingsMain : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultSettingsMain defaultInstance = ((DefaultSettingsMain)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultSettingsMain())));
        
        public static DefaultSettingsMain Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginUserID {
            get {
                return ((string)(this["LoginUserID"]));
            }
            set {
                this["LoginUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LoginUserPassword {
            get {
                return ((string)(this["LoginUserPassword"]));
            }
            set {
                this["LoginUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LoginMeterVarient {
            get {
                return ((int)(this["LoginMeterVarient"]));
            }
            set {
                this["LoginMeterVarient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoginRememberUser {
            get {
                return ((bool)(this["LoginRememberUser"]));
            }
            set {
                this["LoginRememberUser"] = value;
            }
        }
    }
}
