//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationInterface {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class SerialPortSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SerialPortSettings defaultInstance = ((SerialPortSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SerialPortSettings())));
        
        public static SerialPortSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string SerialPort {
            get {
                return ((string)(this["SerialPort"]));
            }
            set {
                this["SerialPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string SignOnBaudRate {
            get {
                return ((string)(this["SignOnBaudRate"]));
            }
            set {
                this["SignOnBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public string CommandBaudRate {
            get {
                return ((string)(this["CommandBaudRate"]));
            }
            set {
                this["CommandBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string StopBits {
            get {
                return ((string)(this["StopBits"]));
            }
            set {
                this["StopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string DataBits {
            get {
                return ((string)(this["DataBits"]));
            }
            set {
                this["DataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string Parity {
            get {
                return ((string)(this["Parity"]));
            }
            set {
                this["Parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3500")]
        public int CommandTimeOut {
            get {
                return ((int)(this["CommandTimeOut"]));
            }
            set {
                this["CommandTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2500")]
        public int IntercharacterDelay {
            get {
                return ((int)(this["IntercharacterDelay"]));
            }
            set {
                this["IntercharacterDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int InterframeTimeout {
            get {
                return ((int)(this["InterframeTimeout"]));
            }
            set {
                this["InterframeTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ServerSAP {
            get {
                return ((int)(this["ServerSAP"]));
            }
            set {
                this["ServerSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("256")]
        public int ServerLowerMacAddress {
            get {
                return ((int)(this["ServerLowerMacAddress"]));
            }
            set {
                this["ServerLowerMacAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int ClientSAP {
            get {
                return ((int)(this["ClientSAP"]));
            }
            set {
                this["ClientSAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte ApplicationContext {
            get {
                return ((byte)(this["ApplicationContext"]));
            }
            set {
                this["ApplicationContext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte SecurityMechanism {
            get {
                return ((byte)(this["SecurityMechanism"]));
            }
            set {
                this["SecurityMechanism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00000000")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int PDUSize {
            get {
                return ((int)(this["PDUSize"]));
            }
            set {
                this["PDUSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Cnf1 {
            get {
                return ((byte)(this["Cnf1"]));
            }
            set {
                this["Cnf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Cnf2 {
            get {
                return ((byte)(this["Cnf2"]));
            }
            set {
                this["Cnf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Cnf3 {
            get {
                return ((byte)(this["Cnf3"]));
            }
            set {
                this["Cnf3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Landis+Gyr\\DLMS MMP\\Configuration\\Instantaneous_c.xml")]
        public string ReadOut {
            get {
                return ((string)(this["ReadOut"]));
            }
            set {
                this["ReadOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Landis+Gyr\\DLMS MMP\\Configuration\\Billing.xml")]
        public string Billing {
            get {
                return ((string)(this["Billing"]));
            }
            set {
                this["Billing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Landis+Gyr\\DLMS MMP\\Configuration\\BillingVZ.xml")]
        public string BillingVZ {
            get {
                return ((string)(this["BillingVZ"]));
            }
            set {
                this["BillingVZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Landis+Gyr\\DLMS MMP\\Configuration\\Tamper.xml")]
        public string TamperXML {
            get {
                return ((string)(this["TamperXML"]));
            }
            set {
                this["TamperXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RJ Port")]
        public string CommunicationPort {
            get {
                return ((string)(this["CommunicationPort"]));
            }
            set {
                this["CommunicationPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mode-E")]
        public string CommunicationMode {
            get {
                return ((string)(this["CommunicationMode"]));
            }
            set {
                this["CommunicationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModemNumber {
            get {
                return ((string)(this["ModemNumber"]));
            }
            set {
                this["ModemNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Landis+Gyr\\DLMS MMP\\Configuration")]
        public string ScaleXMLPath {
            get {
                return ((string)(this["ScaleXMLPath"]));
            }
            set {
                this["ScaleXMLPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("93BC0FABF6C85E9E1C53D78885373DC7")]
        public string HLSKey {
            get {
                return ((string)(this["HLSKey"]));
            }
            set {
                this["HLSKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1CFF3F")]
        public string ConformanceBlock {
            get {
                return ((string)(this["ConformanceBlock"]));
            }
            set {
                this["ConformanceBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000102030405060708090A0B0C0D0E0F")]
        public string HLSPWD {
            get {
                return ((string)(this["HLSPWD"]));
            }
            set {
                this["HLSPWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HDLCAddressing {
            get {
                return ((int)(this["HDLCAddressing"]));
            }
            set {
                this["HDLCAddressing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AddressingSchem {
            get {
                return ((int)(this["AddressingSchem"]));
            }
            set {
                this["AddressingSchem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Authentication {
            get {
                return ((int)(this["Authentication"]));
            }
            set {
                this["Authentication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int DLMSVersion {
            get {
                return ((int)(this["DLMSVersion"]));
            }
            set {
                this["DLMSVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int InformationSize {
            get {
                return ((int)(this["InformationSize"]));
            }
            set {
                this["InformationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int WindowSize {
            get {
                return ((int)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ServerPhysicalID {
            get {
                return ((int)(this["ServerPhysicalID"]));
            }
            set {
                this["ServerPhysicalID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int CosemBufferSize {
            get {
                return ((int)(this["CosemBufferSize"]));
            }
            set {
                this["CosemBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int DLLBufferSize {
            get {
                return ((int)(this["DLLBufferSize"]));
            }
            set {
                this["DLLBufferSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BaudRateSelectedIndex {
            get {
                return ((int)(this["BaudRateSelectedIndex"]));
            }
            set {
                this["BaudRateSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MeterMode {
            get {
                return ((int)(this["MeterMode"]));
            }
            set {
                this["MeterMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dlmspt")]
        public string AppUser {
            get {
                return ((string)(this["AppUser"]));
            }
            set {
                this["AppUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dlmspt@12")]
        public string AppPwd {
            get {
                return ((string)(this["AppPwd"]));
            }
            set {
                this["AppPwd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppUserRememberMe {
            get {
                return ((bool)(this["AppUserRememberMe"]));
            }
            set {
                this["AppUserRememberMe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("08")]
        public string DefaultReadClassID {
            get {
                return ((string)(this["DefaultReadClassID"]));
            }
            set {
                this["DefaultReadClassID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000010000FF")]
        public string DefaultReadOBIS {
            get {
                return ((string)(this["DefaultReadOBIS"]));
            }
            set {
                this["DefaultReadOBIS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string DefaultReadAtt {
            get {
                return ((string)(this["DefaultReadAtt"]));
            }
            set {
                this["DefaultReadAtt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("09")]
        public string DefaultReadDaraType {
            get {
                return ((string)(this["DefaultReadDaraType"]));
            }
            set {
                this["DefaultReadDaraType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0C")]
        public string DefaultReadLen {
            get {
                return ((string)(this["DefaultReadLen"]));
            }
            set {
                this["DefaultReadLen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultReadAccSelector {
            get {
                return ((int)(this["DefaultReadAccSelector"]));
            }
            set {
                this["DefaultReadAccSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultReadCmdType {
            get {
                return ((int)(this["DefaultReadCmdType"]));
            }
            set {
                this["DefaultReadCmdType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("010204020412000809060000010000FF0F02120000090C000E0507FF0C310AFF800000090C000E050" +
            "8FF0C310AFF8000000100")]
        public string DefaultReadSelectiveAccessCommand {
            get {
                return ((string)(this["DefaultReadSelectiveAccessCommand"]));
            }
            set {
                this["DefaultReadSelectiveAccessCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07DD0404040B2527FF800000")]
        public string DefaultReadDataValueCommand {
            get {
                return ((string)(this["DefaultReadDataValueCommand"]));
            }
            set {
                this["DefaultReadDataValueCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string ClientSystemTitle {
            get {
                return ((string)(this["ClientSystemTitle"]));
            }
            set {
                this["ClientSystemTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Securitysuit {
            get {
                return ((int)(this["Securitysuit"]));
            }
            set {
                this["Securitysuit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000102030405060708090A0B0C0D0E0F")]
        public string GlobalEncryptionKey {
            get {
                return ((string)(this["GlobalEncryptionKey"]));
            }
            set {
                this["GlobalEncryptionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DedicatedKey {
            get {
                return ((int)(this["DedicatedKey"]));
            }
            set {
                this["DedicatedKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("000102030405060708090A0B0C0D0E0F")]
        public string AuthenticationKey {
            get {
                return ((string)(this["AuthenticationKey"]));
            }
            set {
                this["AuthenticationKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Non Cyphering")]
        public string AESEncryption {
            get {
                return ((string)(this["AESEncryption"]));
            }
            set {
                this["AESEncryption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte AssociationMode {
            get {
                return ((byte)(this["AssociationMode"]));
            }
            set {
                this["AssociationMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte AssociationType {
            get {
                return ((byte)(this["AssociationType"]));
            }
            set {
                this["AssociationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12345678")]
        public string AssociationAccess {
            get {
                return ((string)(this["AssociationAccess"]));
            }
            set {
                this["AssociationAccess"] = value;
            }
        }
    }
}
